config/routes.rb
Kazdoor::Application.routes.draw do

  get "primary_user/new"
  get "primary_user/show"

  resource :money_program do
    collection do
      get :refresh_user
      post :lookup_user
      post :deposit
      post :withdraw
      post :cashout
      post :unenroll
    end
  end

  resources :invites , :only=>[:show, :index] do
    get "share_link" , :on=>:collection
  end

  resources :like

  resources :states
  resources :countries do
    get 'country_code', :on =>:member
  end
  resources :cities

  resources :neighborhoods

  resources :transaction_types
	devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations=>"users/registrations",
    :password=>"users/passwords",
    :confirmations => "users/confirmations"
  }

  devise_scope :user do
    namespace :users do
      resources :sessions, :only => [:create, :destroy]
      resources :registrations, :only=>[:create]
      resources :passwords, :only=>[:create]
      resources :confirmations, :only=>[:update]
    end
  end

  namespace :users do
    resources :profile, only: [:index] do 
      collection do
        put :update 
      end
    end

		resources :users_snaps do
			get '/qr_code/:qr_code_hash.(:format)'   ,:action=>:snap, :on =>:collection
		end
		resources :places
		resources :receipts do
      get  '/receipts-customer.:format', :action=>:list_receipts_history, :on=>:collection
      get  '/pending-receipts.:format', :action=> :index, :on=>:collection
    end
		resources :rewards do
			get '/claim.:format',:action=>:claim, :on =>:member
    end
    resources :cashiers do
      collection do
        get '/check_role.:format', :action => :check_user_role
        get '/business/:business_id/items.:format', :action => :list_engagements_items
        post '/ring_up.:format', :action => :ring_up
        post '/load_money.:format', :action => :load_money
        post '/charge_customer.:format', :action => :charge_customer
        get  '/receipts-merchant.:format', :action => :list_receipts_history
        get '/refund.:format', :action => :refund
      end
    end
    resource :businesses do
      get :savings, :on => :collection
      get :balance, :on => :collection

			get  '/primary_place', :action=>:primary_place, :on =>:collection
			post '/primary_place',:action=>:primary_place,  :on =>:collection
			get  '/set_rewards',  :action=>:set_rewards , :on =>:collection
			get  '/open_sign/:id',  :action=>:open_sign , :on =>:collection
			post '/open_sign/:id',  :action=>:open_sign , :on =>:collection
    end
    get '/list_all_cities.:format', :action=>:list_all_cities,:controller=>:places      
	end
	

  resources :users_snaps
	resources :users_snaps do
		get '/businesses/:business_id/places/:place_id/from_date/:from_date/to_date/:to_date'   ,:action=>:index, :on =>:collection
	end
	resources :loyal_customers
	resources :loyal_customers do
		get '/businesses/:business_id/places/:place_id/from_date/:from_date/to_date/:to_date'   ,:action=>:index, :on =>:collection
	end
	resources :program_types
	resources :programs
	resources :rewards do
	  get "update_businesses/:id"   ,:action=>:update_businesses , :on =>:collection  ,:as =>"update_business"
    get "update_programs/:id"     ,:action=>:update_programs   , :on =>:collection  ,:as =>"update_programs"
    get "update_campaigns/:id"    ,:action=>:update_campaigns  , :on =>:collection  ,:as =>"update_campaigns"
    get "update_items/:id"        ,:action=>:update_items     , :on =>:collection  ,:as =>"update_items"

	end

  resources :places do
		get "/google/:reference_id" , :action =>:google,          :on=>:member,  :as =>"google"
		get "/reset_google" ,         :action =>:reset_google ,   :on=>:member
    get '/for_businessid/:id' ,   :action=>:for_businessid,   :on =>:collection, :as=>"for_businessid"
	end

	resources :users do
    resources :transactions, :controller => 'users/transactions'
  end

  resources :templates

  resources :print_jobs
  resources :brands
  resources :brands do
    get "crop", on: :member
  end

  resources :qr_codes do
    get "update_businesses/:id" , action: :update_businesses, on: :collection , as: "update_business"
    get "update_engagements/:id", action: :update_engagements, on: :collection, as: "update_engagements"
    get "update_programs/:id", action: :update_programs, on: :collection, as: "update_programs"
    get "update_campaigns/:id" , action: :update_campaigns, on: :collection, as: "update_campaigns"
    post "panel", on: :collection
    get  "panel", on: :collection
    post "printable", on: :collection
  end

  resources :activities do
    post "earn", :on => :collection
    post "spend", :on => :collection
  end

  resources :categories , :followers, :term_and_conditions

  resources :accounts do
    resources :reports, :only => [:create, :show, :index]
  end

  resources :transactions, :only => [:index, :show] do
    member do
      post :refund
    end
  end

  resources :businesses do
    
    post :mark_as_featured
    post :mark_as_unfeatured

	  get "update_cities/:id", :action=>:update_cities, :on =>:collection, :as =>"update_cities"
	  get "update_users/:id", :action=>:update_users, :on =>:collection, :as =>"update_users"
	  get '/update_currencies/:country_id', :action=>:update_currencies, :on=> :collection, :as=>"update_currencies"
	  get "update_countries.:format",:action=>:update_countries, :on =>:collection, :as =>"update_countries"
	  get "check_primary_place/:id", :action=>:check_primary_place , :on =>:collection ,:as =>"check_primary_place"
	  get "list_campaign_transactions/:c_id", :action=> :list_campaign_transactions, :on=>:member, :as=> "list_campaign_transactions"
	  get "list_enrolled_customers/:c_id", :action=> :list_enrolled_customers, :on=>:member, :as=> "list_enrolled_customers"
	  get "list_all_enrolled_customers", :action=> :list_all_enrolled_customers, :on=> :member, :as=>"list_all_enrolled_customers"
    get '/country_code', :action => :country_code, :on =>:member
    get '/choose_campaign_type', :action => :choose_campaign_type, :on => :member
    post '/new_campaign_type', :action => :new_campaign_type, :on => :member

    resources :transactions, :controller => "businesses/transactions", :only => [:index]

    resources :measurement_types, :controller => "businesses/measurement_types"
    resources :items, :controller => "businesses/items"
    resources :places, :controller => "businesses/places" do
      resources :items, :controller => "businesses/places/items"
    end

    resources :programs , :controller => "businesses/programs" do
      resources :campaigns , :controller => "businesses/programs/campaigns" do
        resources :engagements,:controller => "businesses/programs/campaigns/engagements" do
          post "change_status"   ,:on =>:member
	        get "stamps", :on => :collection
        end
        resources :places , :only=>[:issue_code] do
          get "issue_code" ,:on =>:member
        end
	      resources :rewards, :controller=>"businesses/programs/campaigns/rewards" do
	        post "/crop_image",:action=>:crop_image
        end
     end
    end
    resources :rewards
    resources :campaigns,:controller => "businesses/campaigns" do
      post "/crop_image",:action=>:crop_image
    end
    resources :spend_campaigns,:controller => "businesses/spend_campaigns"
    resources :cash_campaigns,:controller => "businesses/cash_campaigns" do
      post '/start_campaign', :action => :start_campaign, :on => :member
      post '/stop_campaign', :action => :stop_campaign, :on => :member
    end

    resource :cashbox, :only => [:show, :edit, :update], :controller => "businesses/cashboxes"
  end
  resources :users_management do
    member do
      post "withdraw_account", :action =>:withdraw_account, :as=>"withdraw_account"
      post "deposit_account", :action =>:deposit_account, :as=>"deposit_account"
      post "redeem_rewards", :action =>:redeem_reward_for_user, :as=>"redeem_rewards"
      post "make_engagement", :action =>:make_engagement, :as=>"make_engagement"
      get  "transactions/business/:business_id/programs/:program_id",:action=>:list_transactions, :as =>"list_transactions"
      get  "list_campaigns/business/:business_id/programs/:program_id",:action=>:list_campaigns, :as =>"list_campaigns"
      get  "manage_user_accounts", :action =>:manage_user_accounts, :as=>:manage_user_accounts
      get  "redeem_rewards", :action =>:redeem_rewards, :as=>:redeem_rewards
      get  "list_engagements", :action =>:list_engagements, :as=>"list_engagements"
      get  "logged_actions", :action =>:logged_actions, :as=>"logged_actions"
      get  "all_qr_codes_transactions", :action =>:all_qr_codes_transactions, :as=>"all_qr_codes_transactions"
      get  "view_tx_details/log/:log_id", :action =>:view_tx_details, :as=>"view_tx_details"
      get  "check_txs_updates/:qr_code_id", :action => :check_txs_updates, :as=>"check_txs_updates"
      get  "transactions_report", :action => :aggregate_transactions_report, :as=>"aggregate_transactions_report"
      post :clear_image
    end

    get  "update_cities/:id",:action=>:update_cities , :on =>:collection ,:as =>"update_cities"
    post "check_attribute_availability", :action=>:check_attribute_availability,:on =>:collection ,:as =>"check_attribute_availability"
    post "resend_password", :action=>:resend_password,:on =>:collection ,:as =>"resend_password"
    post "send_confirmation_email", :action=>:send_confirmation_email,:on =>:collection ,:as =>"send_confirmation_email"

    post :enroll_in_money_program

    collection do 
      get :edit
      put :update      
    end
  end

  resources :devices do
    member do
      get :authorize
      get :deauthorize 
    end
  end
  match '/foryou'             						=> "followers#index", :as => :foryou
  match '/foryourbiz'         						=> "followers#new", :as => :foryourbiz
  match '/business_signup'                => "home#business_signup"

app/controllers/businesses/campaigns/engagements_controller.rb
require 'uri'
require 'open-uri'

class Businesses::Programs::EngagementsController < ApplicationController
  before_filter :authenticate_user!,:require_admin, :except => [:index, :show, :stamps]
  before_filter :find_business_and_program_and_places
  
  before_filter :except => :display
  
  def index
    @engagements = @program.engagements
    respond_to do |format|
      format.html
      format.xml { render :xml => @engagements }
      format.json { render :text => @engagements.to_json}
    end
  end
  
  def show
    @engagement = @program.engagements.find(params[:id])
    
    respond_to do |format|
      format.pdf do
        render  :pdf => "#{@business.name}_qrcode"
      end
      format.html
      format.xml { render :xml => @engagement }
      format.json { render :text => @engagement.to_json}
    end
  end

  
  def new
    @engagement = Engagement.new
  end
  
  def create
    @engagement = @program.engagements.new(params[:engagement])
    if @engagement.save
      flash[:notice] = "Successfully created engagement."
      redirect_to business_program_engagement_url(@program, @program, @engagement)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @engagement = Engagement.find(params[:id])
  end
  
  def update
    @engagement = Engagement.find(params[:id])
    
    if @engagement.update_attributes(params[:engagement])
      flash[:notice] = "Successfully updated engagement."
      redirect_to business_program_engagement_url(@business, @program, @engagement)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @engagement = Engagement.find(params[:id])
    @engagement.destroy
    flash[:notice] = "Successfully destroyed engagement."
    redirect_to business_program_engagements_url(@program)
  end

  def display
    @engagement = Engagement.find(params[:id])
    
    respond_to do |format|
      format.html
      format.xml
      format.json
    end
  end
  
  # => Author: Rajib Ahmed
  def stamps
    @engagements = Engagement.where(:program_id=>params[:program_id] , :engagement_type => QrCode::STAMP)    
    respond_to do |format|
      format.html
      format.xml { render :xml => @engagements }
      format.json { render :text => @engagements.to_json}
    end
  end

  
  def issue_code
    @qrcode = QrCode.where( :place_id => params[:id], :engagement_id=>params[:engagement_id] ).first
    if @qrcode.blank? 
      @qrcode = QrCode.create( :place_id=>params[:id] , :engagement_id=> params[:engagement_id]).save!
    else 
      @qrcode.save
    end

    respond_to do |format|
      format.html
      format.js
    end    
  end
    

  private
  def find_business_and_program_and_places
    @program = Program.find(params[:program_id])
    @business = @program.business
    @places = @business.places
    
  end
  
  def save_image(url)
     open("#{RAILS_ROOT}/public/images/qrcodes/image.png","wb")  do |io|
       io << open(URI.parse(url)).read
     end
  end
  
end

app/controllers/businesses/campaigns/rewards_controller.rb
class Businesses::Programs::RewardsController < ApplicationController
  before_filter :authenticate_user!,:require_admin, :except => [:index]
  before_filter :find_business_and_program
  before_filter :places_under_business

  def index
    @rewards = @program.rewards
    respond_to do |format|
      format.html
      format.xml { render :xml => @rewards }
      format.json { render :text => @rewards.to_json }
    end
  end
  
  def show
    @reward = Reward.find(params[:id])
  end
  
  def new
    @reward = Reward.new
  end
  
  def create
    @reward = @program.rewards.new(params[:reward])
    if @reward.save
      flash[:notice] = "Successfully created reward."
      redirect_to business_program_reward_url(@business,@program,@reward)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @reward = Reward.find(params[:id])
  end
  
  def update
    
    @reward = Reward.find(params[:id])
    if @reward.update_attributes(params[:reward])
      flash[:notice] = "Successfully updated reward."
      redirect_to business_program_reward_url(@business, @program, @reward)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    flash[:notice] = "Successfully destroyed reward."
    redirect_to business_program_rewards_url(@business, @program)
  end
  
  private
  def find_business_and_program
    @program     = Program.find(params[:program_id])
    @business    = @program.business
    @engagements = @program.engagements.stamps
  end

  def places_under_business
    @places ||= Place.where(:business_id => params[:business_id]) 
  end
end

app/controllers/businesses/cashboxes_controller.rb
class Businesses::CashboxesController < ApplicationController
  before_filter :find_business

  def edit
    @account = @business.cashbox
    @account_option = @account.account_option || @account.create_account_option
  end

  def update
    @account = @business.cashbox
    @account_option = @account.account_option

    if @account_option.update_attributes params[:account_option]
      flash[:notice] = "Cashbox settings updated."
      redirect_to [@business, @business.money_program]
    else
      render :edit
    end
  end

  protected
  def find_business
    @business = Business.find params[:business_id]
  end
end

app/controllers/businesses/items_controller.rb
class Businesses::ItemsController < ApplicationController
 before_filter :authenticate_user!, :require_admin
 before_filter :prepare_business
 
 
  def index
    @items = Item.where(:business_id => @business.id)
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def new
    @item = @business.items.build
    @item.build_item_image
  end
 
  def create
    @item = @business.items.build(params[:item])
    if @item.save! && (@item.item_image.nil? || !@item.item_image.need_cropping)
      redirect_to(business_item_url(@business,@item), :notice => 'Item was successfully created.') 
    else
      render :action => 'crop'  
    end
  #rescue
  #  respond_to do |format|
  #    @item.build_item_image if @item.item_image.nil?
  #    format.html { render :action => "new" }
  #    format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
  #  end
  end
 
  def edit
    @item = Item.find(params[:id])
    @item.build_item_image if @item.item_image.nil?
  end
  
  def update
    @item = Item.find(params[:id])
    respond_to do |format|
      if @item.update_attributes!(params[:item])
        format.html { 
          if params[:item][:item_image_attributes][:photo].blank? || !@item.item_image.need_cropping
            redirect_to(business_item_url(@business,@item), :notice => 'item was successfully updated.') 
          else 
            render :action=> 'crop'
          end
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  rescue
    @item.build_item_image if @item.item_image.nil?
    respond_to do |format|
      format.html { render :action => "edit" }
      format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:notice] = "Successfully destroyed Item."
    redirect_to business_items_url(@business)
  end
  
  def crop
    
  end
 
  private 
  def prepare_business
    @business = Business.find(params[:business_id])
  end
 
end

app/helpers/businesses/cash_campaigns_helper.rb
module Businesses::CashCampaignsHelper
end

app/helpers/businesses/cashbox_helper.rb
module Businesses::CashboxHelper
end

app/views/businesses/check_primary_place.js.erb
<% y @business %>
if(<%=raw @business.is_any_primary? %>){
  jQuery('#primary_place').remove();
}else{
  jQuery('#primary_place').show();
}

app/views/businesses/choose_campaign_type.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag "choose_campaign_type" %>
<% end %>
<%= form_tag(new_campaign_type_business_path(@business)) do %>
<h1><%= @business.name %> -> Add Campaign</h1>
<h2>Marketing Goal :: Attach new Customers to my business</h2>
<i>Select a campaign designed to help you attract new customers</i>
<ul class="campaign_types">
  <li>
    <label>
    <input type="radio" name="type" value="cash_incentive"/> 
    <h3>1. Offer a cash incentive</h3>
    <div>ex: Offer a 10$ to get new customer to try your business.</div>
    <div>How to redeem: The cash incentive is deposited in the consumer's cashbox (cashbury account) and discounted after each tender untill fully utilizes</div>
    </label>
  </li>
</ul>

<h2>Marketing Goal :: Retain & Grow my customer base</h2>
<i>Select a campaign designed to help you retain and grow your existing customer base</i>
<ul class="campaign_types">
  <li>
    <label>
    <input type="radio" name="type" value="stamp_card"/> 
    <h3>1. Offer a reword from the menu (Stamp Card)</h3>
    <div>ex: Buy 10 coffee drinks, Get 1 Free</div>
    <div>How to redeem: Customer flashes the redeem receipt to the merchant</div>
    </label>
  </li>
  <li>
    <label>
    <input type="radio" name="type" value="cash_reward"/> 
    <h3>2. Offer a cash reward</h3>
    <div>ex: Spend $100, Get $10 cash back (10% saving)</div>
    <div>
      How to redeem: Cash reward is deposited in the user's cash account and
      discounted at each tender until fully utilized
    </div>
    </label>
  </li>
</ul>
<%= submit_tag("Create") %>
<% end %>
<%= link_to 'Back to business', business_path(@business) %>

app/views/businesses/edit.html.erb
<% title "Edit Business | #{@business.name}" %>

<%= render 'form' %>

<p><%= link_to "Back to List", businesses_path %></p>

app/views/businesses/new.html.erb
<% title "New Business" %>

<%= render 'form' %>

<p><%= link_to "Back to List", businesses_path %></p>

app/views/businesses/show.html.erb
<% title "Business | #{@business.name}" %>
<% content_for (:head) do %>
    <style type="text/css" media="screen">
        table th, td {
            width: 150px;
        }
    </style>
<% end %>
<h3>Category</h3>
<p>
<ol>
    <% for category in @business.categories %>
        <li><%= h category.name %></li>
    <% end %>
</ol>
</p>
<p>
    <strong>Brand:</strong>
    <%= @business.brand.try(:name) %>
</p>

<p>
    <strong>Featured?:</strong>
    <%= @business.featured %>
</p>

<p>
    <strong>Name:</strong>
    <%= @business.name %>
</p>
<p>
    <strong>Description:</strong>
    <%= @business.description %>
</p>
<p>
    <strong>Currency:</strong>
    <%= @business.currency_code %>
</p>
<p>
    <strong>Tag List:</strong>
    <%= @business.tag_list %>
</p>
<p>
    <strong>Country:</strong>
    <%= @business.country.try(:name) %>
</p>
<p>
    <strong>Business Legal Ids:</strong>
    <% @business.legal_ids.each do |legal| %>
    <p><%= LegalType.find(legal.legal_type_id).displayed_type %> : <%= legal.id_number %></p>
<% end %>
</p>

<p>
    <strong>Users IDs Activated?</strong>
    <%= @business.activate_users_id ? "Active" : "In-active" %>
</p>
<p>
    <strong><%= "#{@business.users.length} Customers - " %></strong>
    <%= link_to "View", list_all_enrolled_customers_business_path(@business) %>
</p>
<% unless @business.mailing_address.blank? %>
    <h3>Mailing Address</h3>
    <ul>
        <li><strong>Street Address: </strong><%= @business.mailing_address.street_address %></li>
        <li><strong>Country: </strong><%= @business.mailing_address.city.try(:country).try(:name) %></li>
        <li><strong>City: </strong><%= @business.mailing_address.city.try(:name) %></li>
        <li><strong>ZipCode: </strong><%= @business.mailing_address.zipcode %></li>
    </ul>
<% end %>
<% unless @business.billing_address.blank? %>
    <h3>Billing Address</h3>
    <ul>
        <li><strong>Street Address: </strong><%= @business.billing_address.street_address %></li>
        <li><strong>Country: </strong><%= @business.billing_address.city.try(:country).try(:name) %></li>
        <li><strong>City: </strong><%= @business.billing_address.city.try(:name) %></li>
        <li><strong>ZipCode: </strong><%= @business.billing_address.zipcode %></li>
    </ul>
<% end %>
<h3>Branches</h3>
<table class="mono-table" width="100%" border="1" cellspacing="0" cellpadding="0">
    <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Neiborhood</th>
        <th>Phone Number</th>
        <th>City</th>
        <th>Country</th>
        <th>Zipcode</th>
    </tr>
    <% for place in @business.places %>
        <tr>
            <td><%= link_to place.name, business_place_path(@business, place) %></td>
            <td><%= place.try(:address).try(:street_address) %>   </td>
            <td><%= place.try(:address).try(:neighborhood) %>     </td>
            <td><%= place.phone %>                                </td>
            <td><%= place.try(:address).try(:city).try(:name) %>  </td>
            <td><%= place.try(:address).try(:city).try(:country).try(:name) %></td>
            <td><%= place.try(:address).try(:zipcode) %></td>
        </tr>
    <% end %>
</table>
<p>
    <%= link_to "Edit", edit_business_path(@business) %> |
    <%= link_to "View All", businesses_path %> |
    <%= button_to "Destroy", @business, :confirm => 'Are you sure?', :method => :delete %>
</p>
<p>
  <%= link_to "Current offers", business_campaigns_path(@business) %><br />
  <%= link_to "Show Programs", business_programs_path(@business) %><br />
  <%= link_to "Show Items", business_items_path(@business)  %><br />
  <%= link_to 'Transaction logs', business_transactions_path(@business) %><br />
  <li><%= link_to "New Measurement Type", new_business_measurement_type_path(@business) %></li>
</p>



<script>
    $(function() {
        $("#tabs").tabs();
    });
</script>

<h3>Money Program</h3>
<% if @business.has_money_program? %>
  <h4>Cashbox balance: <%= number_to_currency(@business.cashbox.amount) %> </h4>

  <div>
    <%= number_to_currency(@business.total_cash_loaded_by_customers) %> loaded by
    <%= @business.total_customers_that_loaded_money %> customers.
  </div>

  <div>
    <%= number_to_currency(@business.total_cash_spent_by_customers) %> spent by
    <%= @business.total_customers_that_spent_money %>
  </div>

  <div>
    <%= @business.total_customers_with_cash_in_pocket %>
    still have 
    <%= number_to_currency(@business.total_cash_carried_by_customers) %>
    loaded.
  </div>
  <p><%= link_to 'Transaction logs', business_transactions_path(@business) %></p>
    <div style='border:2px solid gray; padding: 5px 10px;'>
      <p>Lookup customer by email</p>
      <div id='money_program_notice'>    
      </div>  
      <% form_tag lookup_user_money_program_path(:format => 'html'), :remote => true, 'data-update' => '#money_program_lookup' do %>
        <%= text_field_tag 'email' %>
        <%= hidden_field_tag 'business_id', @business.id %>
        <%= submit_tag 'Go' %>
      <% end %>

      <div id='money_program_lookup'></div>
</div>
<% else %>
  <p>Your business is not enrolled in a money program.</p>
<% end %>

<a href="<%= choose_campaign_type_business_path(@business) %>" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" style="float: right;">
  <span class="ui-button-text">+ add campaign</span>
</a>
<h3>Marketing</h3>
<div>
    <div id="tabs">
        <ul>
            <li><a href="#Customer-Acquistion">Customer Acquistion</a></li>
            <li><a href="#Customer-Retention">Customer Retention</a></li>
        </ul>
        <div id="Customer-Acquistion">
            <table class="mono-table" width="100%" border="1" cellspacing="0" cellpadding="0" style="width: 840px;">
                <tr>
                    <th>Campaign</th>
                    <th>Program Type</th>
                    <th>View Transactions</th>
                    <th>View Enrolled customers</th>
                </tr>
                <% for program in @campaigns %>
                    <% actual_campaign = Campaign.where('id' => program.c_id)[0] %>
                    <% if actual_campaign.ctype != 1 && actual_campaign.ctype != 3 %>
                        <tr>                            
			    <% if actual_campaign.ctype == Campaign::CTYPE[:cash_incentive] %>
			    <td><%= link_to program.c_name, business_cash_campaign_path(@business, actual_campaign) %></td>
                            <td><%= program.pt_name %> 
			      <% if actual_campaign.end_date && (actual_campaign.end_date > DateTime.now) %>
			      <%= link_to('Stop', stop_campaign_business_cash_campaign_path(@business, actual_campaign), :remote => true, :method => :post) %>
			      <% else %>
			      <%= link_to('Start', start_campaign_business_cash_campaign_path(@business, actual_campaign), :remote => true, :method => :post) %>
			      <% end %>
			    </td>
			    <% else%>
			    <td><%= link_to program.c_name, business_campaign_path(@business, actual_campaign) %></td>
			    <td><%= program.pt_name %></td>
			    <% end %>
                            <td><%= link_to "View Txs", list_campaign_transactions_business_path(@business, program.c_id) %></td>
                            <td><%= link_to "View Enrolled Customers", list_enrolled_customers_business_path(@business, program.c_id) %></td>
                        </tr>
                    <% end %>
                <% end %>
            </table>
        </div>
        <div id="Customer-Retention">
            <table table class="mono-table" width="100%" border="1" cellspacing="0" cellpadding="0" style="width: 840px;">
                <tr>
                    <th>Campaign</th>
                    <th>Program Type</th>
                    <th>View Transactions</th>
                    <th>View Enrolled customers</th>
                </tr>
                <% for program in @campaigns %>
                    <% actual_campaign = Campaign.where('id' => program.c_id)[0] %>
                    <% if actual_campaign.ctype == 1 || actual_campaign.ctype == 3 %>
                        <tr>
                            <td><%= link_to program.c_name, business_spend_campaign_path(@business, actual_campaign) %></td>
                            <td><%= program.pt_name %></td>
                            <td><%= link_to "View Txs", list_campaign_transactions_business_path(@business, program.c_id) %></td>
                            <td><%= link_to "View Enrolled Customers", list_enrolled_customers_business_path(@business, program.c_id) %></td>
                        </tr>
                    <% end %>
                <% end %>
            </table>
        </div>
    </div>

</div>

app/views/businesses/transactions.html.erb
<% title raw("All Businesses &rarr; Transactions") %>

<%= render :partial => 'businesses/transactions/transaction_list', :object => @transactions %>

<br />

<%= link_to 'Back', businesses_path %>

app/views/businesses/update_cities.js.erb
<%=raw @cities.to_json %>

app/views/businesses/update_countries.js.erb
<%=raw @cities.to_json %>