config/routes.rb
Kazdoor::Application.routes.draw do

  get "primary_user/new"
  get "primary_user/show"

  resource :money_program do
    collection do
      get :refresh_user
      post :lookup_user
      post :deposit
      post :withdraw
      post :cashout
      post :unenroll
    end
  end

  resources :invites , :only=>[:show, :index] do
    get "share_link" , :on=>:collection
  end

  resources :like

  resources :states
  resources :countries do
    get 'country_code', :on =>:member
  end
  resources :cities

  resources :neighborhoods

  resources :transaction_types
	devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations=>"users/registrations",
    :password=>"users/passwords",
    :confirmations => "users/confirmations"
  }

  devise_scope :user do
    namespace :users do
      resources :sessions, :only => [:create, :destroy]
      resources :registrations, :only=>[:create]
      resources :passwords, :only=>[:create]
      resources :confirmations, :only=>[:update]
    end
  end

  namespace :users do
    resources :profile, only: [:index] do 
      collection do
        put :update 
      end
    end

		resources :users_snaps do
			get '/qr_code/:qr_code_hash.(:format)'   ,:action=>:snap, :on =>:collection
		end
		resources :places
		resources :receipts do
      get  '/receipts-customer.:format', :action=>:list_receipts_history, :on=>:collection
      get  '/pending-receipts.:format', :action=> :index, :on=>:collection
    end
		resources :rewards do
			get '/claim.:format',:action=>:claim, :on =>:member
    end
    resources :cashiers do
      collection do
        get '/check_role.:format', :action => :check_user_role
        get '/business/:business_id/items.:format', :action => :list_engagements_items
        post '/ring_up.:format', :action => :ring_up
        post '/load_money.:format', :action => :load_money
        post '/charge_customer.:format', :action => :charge_customer
        get  '/receipts-merchant.:format', :action => :list_receipts_history
        get '/refund.:format', :action => :refund
      end
    end
    resource :businesses do
      get :savings, :on => :collection
      get :balance, :on => :collection

			get  '/primary_place', :action=>:primary_place, :on =>:collection
			post '/primary_place',:action=>:primary_place,  :on =>:collection
			get  '/set_rewards',  :action=>:set_rewards , :on =>:collection
			get  '/open_sign/:id',  :action=>:open_sign , :on =>:collection
			post '/open_sign/:id',  :action=>:open_sign , :on =>:collection
    end
    get '/list_all_cities.:format', :action=>:list_all_cities,:controller=>:places      
	end
	

  resources :users_snaps
	resources :users_snaps do
		get '/businesses/:business_id/places/:place_id/from_date/:from_date/to_date/:to_date'   ,:action=>:index, :on =>:collection
	end
	resources :loyal_customers
	resources :loyal_customers do
		get '/businesses/:business_id/places/:place_id/from_date/:from_date/to_date/:to_date'   ,:action=>:index, :on =>:collection
	end
	resources :program_types
	resources :programs
	resources :rewards do
	  get "update_businesses/:id"   ,:action=>:update_businesses , :on =>:collection  ,:as =>"update_business"
    get "update_programs/:id"     ,:action=>:update_programs   , :on =>:collection  ,:as =>"update_programs"
    get "update_campaigns/:id"    ,:action=>:update_campaigns  , :on =>:collection  ,:as =>"update_campaigns"
    get "update_items/:id"        ,:action=>:update_items     , :on =>:collection  ,:as =>"update_items"

	end

  resources :places do
		get "/google/:reference_id" , :action =>:google,          :on=>:member,  :as =>"google"
		get "/reset_google" ,         :action =>:reset_google ,   :on=>:member
    get '/for_businessid/:id' ,   :action=>:for_businessid,   :on =>:collection, :as=>"for_businessid"
	end

	resources :users do
    resources :transactions, :controller => 'users/transactions'
  end

  resources :templates

  resources :print_jobs
  resources :brands
  resources :brands do
    get "crop", on: :member
  end

  resources :qr_codes do
    get "update_businesses/:id" , action: :update_businesses, on: :collection , as: "update_business"
    get "update_engagements/:id", action: :update_engagements, on: :collection, as: "update_engagements"
    get "update_programs/:id", action: :update_programs, on: :collection, as: "update_programs"
    get "update_campaigns/:id" , action: :update_campaigns, on: :collection, as: "update_campaigns"
    post "panel", on: :collection
    get  "panel", on: :collection
    post "printable", on: :collection
  end

  resources :activities do
    post "earn", :on => :collection
    post "spend", :on => :collection
  end

  resources :categories , :followers, :term_and_conditions

  resources :accounts do
    resources :reports, :only => [:create, :show, :index]
  end

  resources :transactions, :only => [:index, :show] do
    member do
      post :refund
    end
  end

  resources :businesses do
    
    post :mark_as_featured
    post :mark_as_unfeatured

	  get "update_cities/:id", :action=>:update_cities, :on =>:collection, :as =>"update_cities"
	  get "update_users/:id", :action=>:update_users, :on =>:collection, :as =>"update_users"
	  get '/update_currencies/:country_id', :action=>:update_currencies, :on=> :collection, :as=>"update_currencies"
	  get "update_countries.:format",:action=>:update_countries, :on =>:collection, :as =>"update_countries"
	  get "check_primary_place/:id", :action=>:check_primary_place , :on =>:collection ,:as =>"check_primary_place"
	  get "list_campaign_transactions/:c_id", :action=> :list_campaign_transactions, :on=>:member, :as=> "list_campaign_transactions"
	  get "list_enrolled_customers/:c_id", :action=> :list_enrolled_customers, :on=>:member, :as=> "list_enrolled_customers"
	  get "list_all_enrolled_customers", :action=> :list_all_enrolled_customers, :on=> :member, :as=>"list_all_enrolled_customers"
    get '/country_code', :action => :country_code, :on =>:member
    get '/choose_campaign_type', :action => :choose_campaign_type, :on => :member
    post '/new_campaign_type', :action => :new_campaign_type, :on => :member

    resources :transactions, :controller => "businesses/transactions", :only => [:index]

    resources :measurement_types, :controller => "businesses/measurement_types"
    resources :items, :controller => "businesses/items"
    resources :places, :controller => "businesses/places" do
      resources :items, :controller => "businesses/places/items"
    end

    resources :programs , :controller => "businesses/programs" do
      resources :campaigns , :controller => "businesses/programs/campaigns" do
        resources :engagements,:controller => "businesses/programs/campaigns/engagements" do
          post "change_status"   ,:on =>:member
	        get "stamps", :on => :collection
        end
        resources :places , :only=>[:issue_code] do
          get "issue_code" ,:on =>:member
        end
	      resources :rewards, :controller=>"businesses/programs/campaigns/rewards" do
	        post "/crop_image",:action=>:crop_image
        end
     end
    end
    resources :rewards
    resources :campaigns,:controller => "businesses/campaigns" do
      post "/crop_image",:action=>:crop_image
    end
    resources :spend_campaigns,:controller => "businesses/spend_campaigns"
    resources :cash_campaigns,:controller => "businesses/cash_campaigns" do
      post '/start_campaign', :action => :start_campaign, :on => :member
      post '/stop_campaign', :action => :stop_campaign, :on => :member
    end

    resource :cashbox, :only => [:show, :edit, :update], :controller => "businesses/cashboxes"
  end
  resources :users_management do
    member do
      post "withdraw_account", :action =>:withdraw_account, :as=>"withdraw_account"
      post "deposit_account", :action =>:deposit_account, :as=>"deposit_account"
      post "redeem_rewards", :action =>:redeem_reward_for_user, :as=>"redeem_rewards"
      post "make_engagement", :action =>:make_engagement, :as=>"make_engagement"
      get  "transactions/business/:business_id/programs/:program_id",:action=>:list_transactions, :as =>"list_transactions"
      get  "list_campaigns/business/:business_id/programs/:program_id",:action=>:list_campaigns, :as =>"list_campaigns"
      get  "manage_user_accounts", :action =>:manage_user_accounts, :as=>:manage_user_accounts
      get  "redeem_rewards", :action =>:redeem_rewards, :as=>:redeem_rewards
      get  "list_engagements", :action =>:list_engagements, :as=>"list_engagements"
      get  "logged_actions", :action =>:logged_actions, :as=>"logged_actions"
      get  "all_qr_codes_transactions", :action =>:all_qr_codes_transactions, :as=>"all_qr_codes_transactions"
      get  "view_tx_details/log/:log_id", :action =>:view_tx_details, :as=>"view_tx_details"
      get  "check_txs_updates/:qr_code_id", :action => :check_txs_updates, :as=>"check_txs_updates"
      get  "transactions_report", :action => :aggregate_transactions_report, :as=>"aggregate_transactions_report"
      post :clear_image
    end

    get  "update_cities/:id",:action=>:update_cities , :on =>:collection ,:as =>"update_cities"
    post "check_attribute_availability", :action=>:check_attribute_availability,:on =>:collection ,:as =>"check_attribute_availability"
    post "resend_password", :action=>:resend_password,:on =>:collection ,:as =>"resend_password"
    post "send_confirmation_email", :action=>:send_confirmation_email,:on =>:collection ,:as =>"send_confirmation_email"

    post :enroll_in_money_program

    collection do 
      get :edit
      put :update      
    end
  end

  resources :devices do
    member do
      get :authorize
      get :deauthorize 
    end
  end
  match '/foryou'             						=> "followers#index", :as => :foryou
  match '/foryourbiz'         						=> "followers#new", :as => :foryourbiz
  match '/business_signup'                => "home#business_signup"

app/controllers/businesses/campaigns/rewards_controller.rb
class Businesses::Programs::RewardsController < ApplicationController
  before_filter :authenticate_user!,:require_admin, :except => [:index]
  before_filter :find_business_and_program
  before_filter :places_under_business

  def index
    @rewards = @program.rewards
    respond_to do |format|
      format.html
      format.xml { render :xml => @rewards }
      format.json { render :text => @rewards.to_json }
    end
  end
  
  def show
    @reward = Reward.find(params[:id])
  end
  
  def new
    @reward = Reward.new
  end
  
  def create
    @reward = @program.rewards.new(params[:reward])
    if @reward.save
      flash[:notice] = "Successfully created reward."
      redirect_to business_program_reward_url(@business,@program,@reward)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @reward = Reward.find(params[:id])
  end
  
  def update
    
    @reward = Reward.find(params[:id])
    if @reward.update_attributes(params[:reward])
      flash[:notice] = "Successfully updated reward."
      redirect_to business_program_reward_url(@business, @program, @reward)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    flash[:notice] = "Successfully destroyed reward."
    redirect_to business_program_rewards_url(@business, @program)
  end
  
  private
  def find_business_and_program
    @program     = Program.find(params[:program_id])
    @business    = @program.business
    @engagements = @program.engagements.stamps
  end

  def places_under_business
    @places ||= Place.where(:business_id => params[:business_id]) 
  end
end

app/controllers/businesses/programs/campaigns/rewards_controller.rb
class Businesses::Programs::Campaigns::RewardsController < ApplicationController
  before_filter :authenticate_user!, :require_admin
  before_filter :find_business_and_program_and_campaign
  before_filter :places_under_business , :items_uder_business

  def index
    @rewards = @campaign.rewards
    respond_to do |format|
      format.html
      format.xml { render :xml => @rewards }
      format.json { render :text => @rewards.to_json }
    end
  end
  
  def show
    @reward = Reward.find(params[:id])
  end
  
  def new
    @reward = Reward.new
    @items  = Reward.get_available_items(@campaign.id)
  end
  
  def create
    @reward = @campaign.rewards.new(params[:reward])
    params[:upload] ||= {}
    unless params[:upload][:photo].blank?
      @image = RewardImage.new()
      @image.uploadable = @reward
      @image.photo= params[:upload][:photo]
    end
    params[:item_id].present? ? @reward.items.replace([Item.find(params[:item_id])]) : @reward.items.delete_all  # supporting one item for now for each reward
    if @reward.save
      @image.save! if @image
      if params[:upload][:photo].blank? || !@image.need_cropping
        flash[:notice] = "Successfully created reward."
        redirect_to business_program_campaign_reward_url(@business,@program,@campaign,@reward)
      else
        render :action=>"crop"
      end
    else
      @items= Reward.get_available_items(@campaign.id)
      render :action => 'new'
    end
  end
  
  def edit
    @reward = Reward.find(params[:id])
    @items  = Reward.get_available_items(@campaign.id)
  end
  
  def update
    @reward = Reward.find(params[:id])
    params[:upload] ||= {}
    unless params[:upload][:photo].blank?
      @reward.reward_image.try(:destroy)
      @image = RewardImage.new()
      @image.uploadable = @reward
      @image.photo= params[:upload][:photo]
    end
    params[:item_id].present? ? @reward.items.replace([Item.find(params[:item_id])]) : @reward.items.delete_all  # supporting one item for now for each reward
    if @reward.update_attributes(params[:reward])
      @image.save! if @image
      if params[:upload][:photo].blank? || !@image.need_cropping
        flash[:notice] = "Successfully updated reward."
        redirect_to business_program_campaign_reward_url(@business, @program, @campaign,@reward)
      else
        render :action=>"crop"
      end        
    else
      @items= Reward.get_available_items(@campaign.id)
      render :action => 'edit'
    end
  end
  def crop_image
    @reward=Reward.find(params[:reward_id])
    if @reward.update_attributes!(params[:reward])
      flash[:notice] = "Successfully updated reward."
      redirect_to business_program_campaign_reward_url(@business,@program,@campaign,@reward)
    else    
      render :action=>"crop"
    end    
  end
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    flash[:notice] = "Successfully destroyed reward."
    redirect_to business_program_campaign_rewards_url(@business, @program, @campaign)
  end
  
  private
  def find_business_and_program_and_campaign
    @program     = Program.find(params[:program_id])
    @business    = @program.business
    @campaign    = Campaign.find(params[:campaign_id]) 
    @engagements = @campaign.engagements.stamps #TODO check this will be sub with what ?
    @items       = [] 
  end

  def places_under_business
    @places ||= Place.where(:business_id => params[:business_id]) 
  end
  def items_uder_business
    @items = Item.where(:business_id => params[:business_id])
  end
end

app/controllers/users/rewards_controller.rb
class Users::RewardsController < Users::BaseController
	def claim
		begin
			reward=Reward.find(params[:id])
			if reward.campaign.nil?
				respond_with_error(ERRORS[:msg_not_related_to_campaign])
			elsif (user_account=reward.campaign.user_account(current_user)).blank?
				respond_with_error(ERRORS[:msg_user_not_enrolled])
			else
		    if user_account.amount < reward.needed_amount 
		    	respond_with_error(ERRORS[:msg_not_enough_credit])
				else
          reward.is_claimed_by(current_user,user_account,params[:place_id],params[:lat],params[:lng])
          respond_to do |format|
            format.xml { render :xml => reward_hash(reward,user_account,reward.campaign),:status=>200 }
          end
				end
			end
    rescue Exception => e
      logger.error "Exception #{e.class}: #{e.message}"
		 	respond_with_error(e.message)
		 end
	end
	
	ERRORS={
  	:msg_not_related_to_campaign=>"Reward not associated to campaign",
  	:msg_user_not_enrolled      =>"User not enrolled with the reward's campaign",
  	:msg_not_enough_credit      =>"Not enough credit"
  }
  
  private
	def reward_hash(reward,account,campaign)
    r = {:redeem => {}}
		r[:redeem].merge!({:business_id      => campaign.program.business.id})
		r[:redeem].merge!({:campaign_id      => campaign.id})
		r[:redeem].merge!({:reward_id        => reward.id})
		r[:redeem].merge!({:account_amount   => account.amount})
    r
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= javascript_include_tag 'prototype' %>
<%= calendar_date_select_includes %>
<% CalendarDateSelect.format=(:iso_date)%>
<script type="text/javascript" language="javascript" charset="utf-8">
//<![CDATA[
jQuery(function(){
  jQuery('select#brand_id').bind('change',function(){
    var brand_id = jQuery(":selected", this).val();
    jQuery.getScript("/rewards/update_businesses/"+brand_id);
  });        
  
  jQuery('select#business_id').bind('change',function(){
    var business_id = jQuery(":selected", this).val();
    jQuery.getScript("/rewards/update_programs/"+business_id);
  }); 
  
  jQuery('select#program_id').bind('change',function(){
    var program_id = jQuery(":selected", this).val();
    jQuery.getScript("/rewards/update_campaigns/"+program_id);
  }); 
  
  jQuery('select#campaign_id').bind('change',function(){
    var campaign_id = jQuery(":selected", this).val();
    jQuery.getScript("/rewards/update_items/"+campaign_id);
  });
  jQuery('#description_field').keydown(function(){
    var desc_text = jQuery(this).val();
    if ( desc_text.length > 84 ){
      jQuery(this).val(desc_text.substring( 0, 84 ));
      alert( 'Description value can only be 84 characters in length.' );
      return false;
    }
    else{
      jQuery('#counter_field').val(84 - desc_text.length);
    }
  });

  
})
//]]>
</script>

<%= f.error_messages %>
<p class="subcap">Rewards are items that your customers can redeem after earning enough points or stamps.</p>
<div id="left_main">
   <div class="row">
     <div class="basic_info_caption1"> Objective</div>
      <select>
        <option value="">Attarct New Customer</option>
        <option value="">Retain Customers</option>
      </select>
      <br />
    </div>
    <div class="row">
     <div class="basic_info_caption1"> Reward Type</div>
      <select>
        <option value="">from the menu – item</option>
      </select> <br />
      <br />
     </div>
 
  <fieldset>
    <legend>Create The card</legend>
    <div class="row">
      <div class="basic_info_caption1">Card Template</div>
      <select><option>punch card</option></select>
    </div> 
    <div class="row">
      <div class="basic_info_caption1">What is the Reward?</div>
      <%= f.text_field :name, :class =>"basic_info_input",:maxlength=>16  %>
    </div>
    <div class="row">
      <div class="basic_info_caption1">Add a Short Description</div>
      <%= f.text_field :heading1, :class=>"basic_info_input", :maxlength=>40%>
    </div>
    <div class="row">
      <div class="basic_info_caption1">Description</div>
      <%= f.text_area :heading2, :class=>"basic_info_input",:id=>"description_field",:maxlength=>84,:rows=>5 %>
    </div>
    <div class="row">
      <input type="text" name="counter" maxlength="3" size="3" value="84" id="counter_field"> chars remaining
    </div>
    <div class="row">
      <div class="basic_info_caption1">Facebook msg when user unlocks a reward</div>
      <%= f.text_field :fb_unlock_msg, :class=>"basic_info_input", :maxlength=>100 %>
    </div>
    <div class="row">
      <div class="basic_info_caption1">Facebook msg when user enjoys a reward</div>
      <%= f.text_field :fb_enjoy_msg, :class=>"basic_info_input", :maxlength=>100 %>
    </div>
    <div class="row">
      <div class="basic_info_caption1">Set the goal required to unlock this reward</div>
      <div id="Enter_Num_Stamp">
        <div class="basic_info_caption1">
          <%= f.text_field :needed_amount ,:class=>'enter_value_g',:id=> "reward_stamps" %>
          <%=@reward.try(:campaign).try(:measurement_type).try(:name)%>
        </div>
      </div>
      <div id="points" class="setgoaltype"></div>
    </div>
    <div class="row">
      <div class="basic_info_caption1">Image</div>
      <input type="file" name="upload[photo]"/><br />
      <small>supported image types: <strong>JPEG, JPG, PNG, BMP</strong></small>
    </div>
    <div class="row">
      <div class="basic_info_caption1">Legal Terms</div>
      <%= f.text_area :legal_term %>
    </div>
  </fieldset>
  <div class="row">
    <div class="basic_info_caption1">Brand</div>
    <p><%= select_tag :brand_id ,"<option value=''>..Select One..</option>".html_safe + options_from_collection_for_select(@brands , :id, :name, @reward.try(:campaign).try(:program).try(:business).try(:brand).try(:id)) %></p>
  </div>
  <div class="row">
    <div class="basic_info_caption1">Business</div>
    <p><%= select_tag :business_id , "<option value=''>..None..</option>".html_safe + options_from_collection_for_select(Business.all , :id, :name, @reward.try(:campaign).try(:program).try(:business).try(:id)) %></p>
  </div>	
  <div class="row">
    <div class="basic_info_caption1">Program</div>
    <p><%= select_tag :program_id , "<option value=''>..None..</option>".html_safe + options_from_collection_for_select(Program.all, :id, :program_type_name, @reward.try(:campaign).try(:program).try(:id)) %></p>
  </div>
  <div class="row">
    <div class="basic_info_caption1">Campaign</div>
    <p><%= select_tag :campaign_id , "<option value=''>..None..</option>".html_safe + options_from_collection_for_select(Campaign.all , :id, :name, @reward.try(:campaign).try(:id)) %></p>
  </div>
  <fieldset>
    <legend>Settings</legend>
    <div class="row">  
         <div class="basic_info_caption1">Item</div>
         <%= select_tag "item_id", "<option value=''>...None...</option>".html_safe+ options_from_collection_for_select(Item.all , :id, :name, @reward.try(:items).try(:first).try(:id)) %><br /> 
    </div>
    <div class="row">
      <div class="basic_info_caption1">Sales Price</div>
      <%= f.text_field :sales_price, :class =>"basic_info_input"  %>
    </div>
    <div class="row">
      <div class="basic_info_caption1">Cost</div>
      <%= f.text_field :cost, :class =>"basic_info_input"  %>
    </div>
    <div class="row">
      <div class="basic_info_caption1">Offer Price</div>
      <%= f.text_field :offer_price, :class =>"basic_info_input"  %>
    </div>
    <div class="row">
      <div class="basic_info_caption1">Total Quantity Available</div>
        <%= f.text_field :max_claim , :class=>"basic_info_input"%>
    </div>
    <div class="row">
      <div class="basic_info_caption1">
        Max Enjoyments Per User
      </div><%= f.text_field :max_claim_per_user , :class=>"basic_info_input"%>
      </div>
      <div class="row">
      <div class="basic_info_caption1">
        Foreign-Identifier
      </div><%= f.text_field :foreign_identifier , :class=>"basic_info_input"%>
      </div>
  </fieldset>
  <div class="row">
    <input type="submit" value="" name="commit" id="save_cont_btn" class="save">
		<%= link_to "Cancel", rewards_path, :class => "cancel right" %>
	</div>
</div>
</div>

app/views/rewards/edit.html.erb
<% title "Edit Reward" %>

<%= form_for @reward, :url => reward_path(@reward), :html => {:multipart => true, :method => :put}  do |f| %>
	<%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

app/views/rewards/index.html.erb
<% title "Rewards" %>

<table width="100%" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <th>Name</th>
    <th>Campaign</th>
  </tr>
  <% for reward in @rewards %>
    <tr>
      <td><%= link_to reward.name, reward_path(reward) %></td>
      <td><%= reward.campaign.try(:name) %></td>
      <td><%= link_to "Edit", edit_reward_path(reward) %></td>
      <td><%= button_to "Destroy", reward_path(reward), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Reward", new_reward_path %></p>

app/views/rewards/new.html.erb
<style type="text/css" media="screen">
  .place-checkbox{float:left; display:block}
</style>

<% title "New Reward" %>

<%= form_for(@reward,:url => rewards_path,:html => { :multipart => true }) do |f| %>
	<%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

app/views/rewards/show.html.erb
<% title "Reward" %>
<div id="left_main">
  <p>
    <strong>Name:</strong>
    <%= @reward.name %>
  </p>
  <p>
    <strong>Short Description:</strong>
    <%= @reward.heading1 %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= @reward.heading2 %>
  </p>
  <p>
    <strong>Facebook msg when user unlocks a reward:</strong>
    <%= @reward.fb_unlock_msg %>
  </p>
  <p>
    <strong>Facebook msg when user enjoys a reward:</strong>
    <%= @reward.fb_enjoy_msg %>
  </p>
  <p>
    <strong>Program:</strong>
    <%= @reward.try(:campaign).try(:program).try(:program_type_name) %>
  </p>
  
  <p>
    <strong>Campaign:</strong>
    <%= @reward.try(:campaign).try(:name)  %>
  </p>
  <p>
    <strong>Needed Amount</strong>
    <%= @reward.needed_amount %>
  </p>
  <p>
    <strong>Cost</strong>
    <%= @reward.cost %>
  </p>
  <p>
    <strong>Sales Price</strong>
    <%= @reward.sales_price %>
  </p>
  <strong>Engagements:</strong>
  <% @reward.campaign.engagements.each do |en| %>
    <ul>
      <li><%= en.name %></li>
    </ul>
  <% end %>
  <p>
    <strong>Photo:</strong>
    <% if @reward.reward_image%>
      <%= image_tag @reward.reward_image.photo.url(:thumb) %>
    <% end %>
  </p>
  <p>
    <strong>Legal Terms:</strong>
    <%= @reward.legal_term  %>
  </p>
  <p>
    <strong>Reward Item:</strong>
    <%= @reward.items.try(:first).try(:name)  %>
  </p>
  <p>
    <strong>Foreign Identifier:</strong>
    <%= @reward.foreign_identifier %>
  </p>
  <p>
    <strong>Total Quantity Available:</strong>
    <%= @reward.max_claim %>
  </p>
  <p>
    <strong>Max Enjoyments Per User:</strong>
    <%= @reward.max_claim_per_user %>
  </p>
  <div>
    <%= link_to "Edit", edit_reward_path(@reward) %> <br />
    <%= link_to "Back to List", rewards_path %> <br />
    <%= button_to "Destroy", reward_path(@reward), :confirm => 'Are you sure?', :method => :delete %> <br /> 
  </div>
</div>

app/views/rewards/update_businesses.js.erb
var options = "<%= escape_javascript("<option value=''>Select....</option>".html_safe + options_from_collection_for_select( @businesses , :id ,:name ))%>"
jQuery('select#business_id').html(options)

app/views/rewards/update_campaigns.js.erb
var options = "<%= escape_javascript("<option value=''>Select....</option>".html_safe + options_from_collection_for_select( @campaigns , :id ,:name ))%>"
jQuery('select#campaign_id').html(options)

app/views/rewards/update_items.js.erb
var options = "<%= escape_javascript("<option value=''>Select....</option>".html_safe + options_from_collection_for_select( @items , :id ,:name ))%>"
jQuery('select#item_id').html(options)

app/views/rewards/update_programs.js.erb
var options = "<%= escape_javascript("<option value=''>Select....</option>".html_safe + options_from_collection_for_select( @programs , :id , :program_type_name ))%>"
jQuery('select#program_id').html(options)