config/routes.rb
Kazdoor::Application.routes.draw do

  get "primary_user/new"
  get "primary_user/show"

  resource :money_program do
    collection do
      get :refresh_user
      post :lookup_user
      post :deposit
      post :withdraw
      post :cashout
      post :unenroll
    end
  end

  resources :invites , :only=>[:show, :index] do
    get "share_link" , :on=>:collection
  end

  resources :like

  resources :states
  resources :countries do
    get 'country_code', :on =>:member
  end
  resources :cities

  resources :neighborhoods

  resources :transaction_types
	devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations=>"users/registrations",
    :password=>"users/passwords",
    :confirmations => "users/confirmations"
  }

  devise_scope :user do
    namespace :users do
      resources :sessions, :only => [:create, :destroy]
      resources :registrations, :only=>[:create]
      resources :passwords, :only=>[:create]
      resources :confirmations, :only=>[:update]
    end
  end

  namespace :users do
    resources :profile, only: [:index] do 
      collection do
        put :update 
      end
    end

		resources :users_snaps do
			get '/qr_code/:qr_code_hash.(:format)'   ,:action=>:snap, :on =>:collection
		end
		resources :places
		resources :receipts do
      get  '/receipts-customer.:format', :action=>:list_receipts_history, :on=>:collection
      get  '/pending-receipts.:format', :action=> :index, :on=>:collection
    end
		resources :rewards do
			get '/claim.:format',:action=>:claim, :on =>:member
    end
    resources :cashiers do
      collection do
        get '/check_role.:format', :action => :check_user_role
        get '/business/:business_id/items.:format', :action => :list_engagements_items
        post '/ring_up.:format', :action => :ring_up
        post '/load_money.:format', :action => :load_money
        post '/charge_customer.:format', :action => :charge_customer
        get  '/receipts-merchant.:format', :action => :list_receipts_history
        get '/refund.:format', :action => :refund
      end
    end
    resource :businesses do
      get :savings, :on => :collection
      get :balance, :on => :collection

			get  '/primary_place', :action=>:primary_place, :on =>:collection
			post '/primary_place',:action=>:primary_place,  :on =>:collection
			get  '/set_rewards',  :action=>:set_rewards , :on =>:collection
			get  '/open_sign/:id',  :action=>:open_sign , :on =>:collection
			post '/open_sign/:id',  :action=>:open_sign , :on =>:collection
    end
    get '/list_all_cities.:format', :action=>:list_all_cities,:controller=>:places      
	end
	

  resources :users_snaps
	resources :users_snaps do
		get '/businesses/:business_id/places/:place_id/from_date/:from_date/to_date/:to_date'   ,:action=>:index, :on =>:collection
	end
	resources :loyal_customers
	resources :loyal_customers do
		get '/businesses/:business_id/places/:place_id/from_date/:from_date/to_date/:to_date'   ,:action=>:index, :on =>:collection
	end
	resources :program_types
	resources :programs
	resources :rewards do
	  get "update_businesses/:id"   ,:action=>:update_businesses , :on =>:collection  ,:as =>"update_business"
    get "update_programs/:id"     ,:action=>:update_programs   , :on =>:collection  ,:as =>"update_programs"
    get "update_campaigns/:id"    ,:action=>:update_campaigns  , :on =>:collection  ,:as =>"update_campaigns"
    get "update_items/:id"        ,:action=>:update_items     , :on =>:collection  ,:as =>"update_items"

	end

  resources :places do
		get "/google/:reference_id" , :action =>:google,          :on=>:member,  :as =>"google"
		get "/reset_google" ,         :action =>:reset_google ,   :on=>:member
    get '/for_businessid/:id' ,   :action=>:for_businessid,   :on =>:collection, :as=>"for_businessid"
	end

	resources :users do
    resources :transactions, :controller => 'users/transactions'
  end

  resources :templates

  resources :print_jobs
  resources :brands
  resources :brands do
    get "crop", on: :member
  end

  resources :qr_codes do
    get "update_businesses/:id" , action: :update_businesses, on: :collection , as: "update_business"
    get "update_engagements/:id", action: :update_engagements, on: :collection, as: "update_engagements"
    get "update_programs/:id", action: :update_programs, on: :collection, as: "update_programs"
    get "update_campaigns/:id" , action: :update_campaigns, on: :collection, as: "update_campaigns"
    post "panel", on: :collection
    get  "panel", on: :collection
    post "printable", on: :collection
  end

  resources :activities do
    post "earn", :on => :collection
    post "spend", :on => :collection
  end

  resources :categories , :followers, :term_and_conditions

  resources :accounts do
    resources :reports, :only => [:create, :show, :index]
  end

  resources :transactions, :only => [:index, :show] do
    member do
      post :refund
    end
  end

  resources :businesses do
    
    post :mark_as_featured
    post :mark_as_unfeatured

	  get "update_cities/:id", :action=>:update_cities, :on =>:collection, :as =>"update_cities"
	  get "update_users/:id", :action=>:update_users, :on =>:collection, :as =>"update_users"
	  get '/update_currencies/:country_id', :action=>:update_currencies, :on=> :collection, :as=>"update_currencies"
	  get "update_countries.:format",:action=>:update_countries, :on =>:collection, :as =>"update_countries"
	  get "check_primary_place/:id", :action=>:check_primary_place , :on =>:collection ,:as =>"check_primary_place"
	  get "list_campaign_transactions/:c_id", :action=> :list_campaign_transactions, :on=>:member, :as=> "list_campaign_transactions"
	  get "list_enrolled_customers/:c_id", :action=> :list_enrolled_customers, :on=>:member, :as=> "list_enrolled_customers"
	  get "list_all_enrolled_customers", :action=> :list_all_enrolled_customers, :on=> :member, :as=>"list_all_enrolled_customers"
    get '/country_code', :action => :country_code, :on =>:member
    get '/choose_campaign_type', :action => :choose_campaign_type, :on => :member
    post '/new_campaign_type', :action => :new_campaign_type, :on => :member

    resources :transactions, :controller => "businesses/transactions", :only => [:index]

    resources :measurement_types, :controller => "businesses/measurement_types"
    resources :items, :controller => "businesses/items"
    resources :places, :controller => "businesses/places" do
      resources :items, :controller => "businesses/places/items"
    end

    resources :programs , :controller => "businesses/programs" do
      resources :campaigns , :controller => "businesses/programs/campaigns" do
        resources :engagements,:controller => "businesses/programs/campaigns/engagements" do
          post "change_status"   ,:on =>:member
	        get "stamps", :on => :collection
        end
        resources :places , :only=>[:issue_code] do
          get "issue_code" ,:on =>:member
        end
	      resources :rewards, :controller=>"businesses/programs/campaigns/rewards" do
	        post "/crop_image",:action=>:crop_image
        end
     end
    end
    resources :rewards
    resources :campaigns,:controller => "businesses/campaigns" do
      post "/crop_image",:action=>:crop_image
    end
    resources :spend_campaigns,:controller => "businesses/spend_campaigns"
    resources :cash_campaigns,:controller => "businesses/cash_campaigns" do
      post '/start_campaign', :action => :start_campaign, :on => :member
      post '/stop_campaign', :action => :stop_campaign, :on => :member
    end

    resource :cashbox, :only => [:show, :edit, :update], :controller => "businesses/cashboxes"
  end
  resources :users_management do
    member do
      post "withdraw_account", :action =>:withdraw_account, :as=>"withdraw_account"
      post "deposit_account", :action =>:deposit_account, :as=>"deposit_account"
      post "redeem_rewards", :action =>:redeem_reward_for_user, :as=>"redeem_rewards"
      post "make_engagement", :action =>:make_engagement, :as=>"make_engagement"
      get  "transactions/business/:business_id/programs/:program_id",:action=>:list_transactions, :as =>"list_transactions"
      get  "list_campaigns/business/:business_id/programs/:program_id",:action=>:list_campaigns, :as =>"list_campaigns"
      get  "manage_user_accounts", :action =>:manage_user_accounts, :as=>:manage_user_accounts
      get  "redeem_rewards", :action =>:redeem_rewards, :as=>:redeem_rewards
      get  "list_engagements", :action =>:list_engagements, :as=>"list_engagements"
      get  "logged_actions", :action =>:logged_actions, :as=>"logged_actions"
      get  "all_qr_codes_transactions", :action =>:all_qr_codes_transactions, :as=>"all_qr_codes_transactions"
      get  "view_tx_details/log/:log_id", :action =>:view_tx_details, :as=>"view_tx_details"
      get  "check_txs_updates/:qr_code_id", :action => :check_txs_updates, :as=>"check_txs_updates"
      get  "transactions_report", :action => :aggregate_transactions_report, :as=>"aggregate_transactions_report"
      post :clear_image
    end

    get  "update_cities/:id",:action=>:update_cities , :on =>:collection ,:as =>"update_cities"
    post "check_attribute_availability", :action=>:check_attribute_availability,:on =>:collection ,:as =>"check_attribute_availability"
    post "resend_password", :action=>:resend_password,:on =>:collection ,:as =>"resend_password"
    post "send_confirmation_email", :action=>:send_confirmation_email,:on =>:collection ,:as =>"send_confirmation_email"

    post :enroll_in_money_program

    collection do 
      get :edit
      put :update      
    end
  end

  resources :devices do
    member do
      get :authorize
      get :deauthorize 
    end
  end
  match '/foryou'             						=> "followers#index", :as => :foryou
  match '/foryourbiz'         						=> "followers#new", :as => :foryourbiz
  match '/business_signup'                => "home#business_signup"

app/models/program_type.rb
# == Schema Information
# Schema version: 20110615133925
#
# Table name: program_types
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class ProgramType < ActiveRecord::Base
  
	has_many :programs, :dependent => :destroy, :foreign_key => 'program_type_id'
	
	AS = {

	  :marketing => "Marketing",
	  :money => "Money"
	}

  def self.[](name)
    ProgramType.where(:name => name).first
  end

end

app/controllers/businesses/campaigns/engagements_controller.rb
require 'uri'
require 'open-uri'

class Businesses::Programs::EngagementsController < ApplicationController
  before_filter :authenticate_user!,:require_admin, :except => [:index, :show, :stamps]
  before_filter :find_business_and_program_and_places
  
  before_filter :except => :display
  
  def index
    @engagements = @program.engagements
    respond_to do |format|
      format.html
      format.xml { render :xml => @engagements }
      format.json { render :text => @engagements.to_json}
    end
  end
  
  def show
    @engagement = @program.engagements.find(params[:id])
    
    respond_to do |format|
      format.pdf do
        render  :pdf => "#{@business.name}_qrcode"
      end
      format.html
      format.xml { render :xml => @engagement }
      format.json { render :text => @engagement.to_json}
    end
  end

  
  def new
    @engagement = Engagement.new
  end
  
  def create
    @engagement = @program.engagements.new(params[:engagement])
    if @engagement.save
      flash[:notice] = "Successfully created engagement."
      redirect_to business_program_engagement_url(@program, @program, @engagement)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @engagement = Engagement.find(params[:id])
  end
  
  def update
    @engagement = Engagement.find(params[:id])
    
    if @engagement.update_attributes(params[:engagement])
      flash[:notice] = "Successfully updated engagement."
      redirect_to business_program_engagement_url(@business, @program, @engagement)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @engagement = Engagement.find(params[:id])
    @engagement.destroy
    flash[:notice] = "Successfully destroyed engagement."
    redirect_to business_program_engagements_url(@program)
  end

  def display
    @engagement = Engagement.find(params[:id])
    
    respond_to do |format|
      format.html
      format.xml
      format.json
    end
  end
  
  # => Author: Rajib Ahmed
  def stamps
    @engagements = Engagement.where(:program_id=>params[:program_id] , :engagement_type => QrCode::STAMP)    
    respond_to do |format|
      format.html
      format.xml { render :xml => @engagements }
      format.json { render :text => @engagements.to_json}
    end
  end

  
  def issue_code
    @qrcode = QrCode.where( :place_id => params[:id], :engagement_id=>params[:engagement_id] ).first
    if @qrcode.blank? 
      @qrcode = QrCode.create( :place_id=>params[:id] , :engagement_id=> params[:engagement_id]).save!
    else 
      @qrcode.save
    end

    respond_to do |format|
      format.html
      format.js
    end    
  end
    

  private
  def find_business_and_program_and_places
    @program = Program.find(params[:program_id])
    @business = @program.business
    @places = @business.places
    
  end
  
  def save_image(url)
     open("#{RAILS_ROOT}/public/images/qrcodes/image.png","wb")  do |io|
       io << open(URI.parse(url)).read
     end
  end
  
end

app/controllers/businesses/campaigns/rewards_controller.rb
class Businesses::Programs::RewardsController < ApplicationController
  before_filter :authenticate_user!,:require_admin, :except => [:index]
  before_filter :find_business_and_program
  before_filter :places_under_business

  def index
    @rewards = @program.rewards
    respond_to do |format|
      format.html
      format.xml { render :xml => @rewards }
      format.json { render :text => @rewards.to_json }
    end
  end
  
  def show
    @reward = Reward.find(params[:id])
  end
  
  def new
    @reward = Reward.new
  end
  
  def create
    @reward = @program.rewards.new(params[:reward])
    if @reward.save
      flash[:notice] = "Successfully created reward."
      redirect_to business_program_reward_url(@business,@program,@reward)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @reward = Reward.find(params[:id])
  end
  
  def update
    
    @reward = Reward.find(params[:id])
    if @reward.update_attributes(params[:reward])
      flash[:notice] = "Successfully updated reward."
      redirect_to business_program_reward_url(@business, @program, @reward)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    flash[:notice] = "Successfully destroyed reward."
    redirect_to business_program_rewards_url(@business, @program)
  end
  
  private
  def find_business_and_program
    @program     = Program.find(params[:program_id])
    @business    = @program.business
    @engagements = @program.engagements.stamps
  end

  def places_under_business
    @places ||= Place.where(:business_id => params[:business_id]) 
  end
end

app/controllers/businesses/programs_controller.rb
class Businesses::ProgramsController < ApplicationController
  before_filter :authenticate_user!, :require_admin
  before_filter :find_business
  before_filter :setup_program_types

  def index
    @programs = @business.programs

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @programs }
    end
  end

  def show
    @program = @business.programs.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @program }
    end
  end

  def new
    @program = Program.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @program }
    end
  end

  def edit
    @program = Program.find(params[:id])
  end

  def create
    @program = @business.programs.new(params[:program])

    respond_to do |format|
      if @program.save
        format.html { redirect_to(business_program_url(@business,@program), :notice => 'Program was successfully created.') }
        format.xml  { render :xml => @program, :status => :created, :location => @program }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @program.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @program = Program.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to(business_program_url(@business, @program), :notice => 'Program was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @program.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to(business_programs_url(@business)) }
      format.xml  { head :ok }
    end
  end
  
  private
  def find_business
    @business = Business.find(params[:business_id])
  end

  def setup_program_types
    @program_types = ProgramType.all
    @program_types.reject! { |pt| pt.id == ProgramType["Money"].id } if @business.has_money_program?
  end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/businesses/programs/campaigns/_form.html.erb
<script type="text/javascript">
 $(document).ready(function(){ 
  $("#measurement_type_selection").change(function () {
    other_option = $(":selected", this).text();
    if(other_option == "Other")
      $('#new_measurement_type_div').show();
    else
      $('#new_measurement_type_div').hide();
  });

  $("#campaign_is_fb_enabled").click(function(e){
    var $cb = $(this);
    if($cb.is(":checked")){
      update_fb_msg();
      enable_fields();
    }else{
    //engagement_type =jQuery("#engagement_type_id").val();
      disable_fields();
    }
  });

  $("#engagement_amount").blur(update_fb_msg);

  update_fb_msg();

  <% unless @campaign.is_fb_enabled? %>
    disable_fields();
  <% end %>
});
function enable_fields(){
  $("#engagement_amount").attr("disabled",false).css({background:""});
  $("#fb_share_msg").attr("disabled", false ).css({background: ""});
}

function disable_fields(){
  $("#engagement_amount").attr("disabled",true).css({background:"#ccc"});
  $("#fb_share_msg").attr("disabled", true ).css({background:"#ccc"});
}

function update_fb_msg(){
  var amount = $("#engagement_amount").val();
  if(amount =="") {
    amount=1;
    $("#engagement_amount").val(1);
  }
  $("#fb_share_msg").val("share on Facebook and earn +"+amount+" point(s)");
}
</script>

<%= form_for([@business,@program,@campaign], :html=>{:class=>"mono-form"}) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag "Who is this campaign offered to?" %>
    <%= select_tag "target_id", "<option value=''>...Everyone...</option>".html_safe+options_from_collection_for_select(Target.all, "id", "display_name",@campaign.targets.first.try(:id)) %>
  </div>
  <div class="field">
    <%= f.label "Campaign Type" %><%= mark_required(@campaign, :measurement_type) %>
    <%= f.select :ctype,Campaign::CTYPE.each_pair{|k,v| [k,v]}  %>
  </div>
  <div class="field">
    <%= f.label "Name #{mark_required(@campaign, :name)}" %>
    <%= f.text_field :name, :class=>"title" %>
  </div>
  <div class="field">
    <%= f.label :start_date %>
    <%= f.text_field :start_date, :value=>Date.today, :class=>"datepicker" %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.text_field :end_date, {:class=>"datepicker"} %>
  </div>
  <div class="field">
    <%= f.label "Measurement type #{mark_required(@campaign, :measurement_type_id)}" %>
    <%= f.select :measurement_type_id,@measurement_types.collect { |mt| [mt.name,mt.id]}, {}, {:id=>"measurement_type_selection"} %>
  </div>
  
  <div class="field" id="new_measurement_type_div" style="display:none">
    <%= label_tag :measurement_name %><br />
    <%= text_field_tag :measurement_name %>
   </div>
  
  <div class="field">
    <%= f.label :initial_amount %>
    <%= f.text_field :initial_amount %>
  </div>
  <div class="field">
    <%= f.label :initial_biz_amount %>
    <%= f.text_field :initial_biz_amount %>
  </div><br />
  <div class="field">
    <fieldset>
      <legend>Facebook Sharing Engagement</legend>
      <%= f.check_box :is_fb_enabled , :class=>"left" %>
      <%= f.label :is_fb_enabled, "Enable Facebook sharing engagment", :id=>"is_fb_enabled", :class=>"left" , :style=>"width:300px"%>
      <div id="fb_settings">
        <% f.fields_for :engagements do |engagement| %>
          <% if  engagement.object.engagement_type_id ==4  %>
            <%= engagement.hidden_field :name , :value=>"Share " %><br/>
            <%= engagement.label :amount , "Earn points by sharing" %>
            <%= engagement.text_field :amount  , :id=> "engagement_amount" , :class=>"title"%>
            <%= engagement.label :fb_engagement_msg , "Message prompt displayed on the reciept of the user" %>
            <%= engagement.text_field :fb_engagement_msg , :id=>"fb_share_msg" , :class=>"title" %>
            <%= engagement.hidden_field :engagement_type_id , :value=>EngagementType.share_id.to_s, :id=>"engagement_type_id" %>
          <% end %>
        <% end %>
      </div>
    </fieldset>
  </div>
  <div class="field">
     <fieldset>
      <legend>Assign Campaign to Places</legend>
      <p>
        <%= f.label :places, "Places" %><br />
        <% @business.places.each do |place| %>
          <% listed_places= @campaign.new_record? ? @business.places : @campaign.places%>
          <%= check_box_tag("campaign[places_list][#{place.id}]", "1", listed_places.detect{|i| i.id == place.id}) %>
          <%= "#{place.name}"%><br />
        <% end %>
      </p>
    </fieldset>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/programs/campaigns/edit.html.erb
<% title "Editing #{@campaign.name}" %>
<%= render 'form' %>

<%= link_to 'Show', business_program_campaign_path(@business,@program,@campaign) %> |
<%= link_to 'Back', business_program_campaigns_path %>

app/views/businesses/programs/campaigns/index.html.erb
<% title "Listing Campaigns" %>

<table class="mono-table" width="100%" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Business</th>
    <th>Program</th>
    <th>Initial user amount</th>
    <th>Initial biz amount</th>
    <th>Measurement Type</th>
    <th>Sharing</th>
    <th></th>
    <th></th>
  </tr>

<% @campaigns.each do |campaign | %>
  <tr>
    <td><%= link_to campaign.name, business_program_campaign_url(@business, @program, campaign)%></td>
    <td><%= campaign.start_date %></td>
    <td><%= campaign.end_date %></td>
    <td><%= campaign.program.try(:business).try(:name) %></td>
    <td><%= campaign.program.try(:program_type_name) %></td>
    <td><%= campaign.initial_amount %></td>
    <td><%= campaign.initial_biz_amount %></td>
    <td><%= campaign.measurement_type.try(:name) %></td>
    <td><%= status_icon campaign.is_fb_enabled?  %></td>

    <td><%= link_to 'Edit', edit_business_program_campaign_path(@business,@program, campaign) , :class=>"button" %></td>
    <td><%= button_to "Destroy", business_program_campaign_path(@business,@program,campaign), :method=>:delete, :class=>:destroy,:confirm=>"Are you sure?" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Campaign', new_business_program_campaign_path ,:class=>"button positive"%><br />

app/views/businesses/programs/campaigns/new.html.erb
<% title "New campaign" %>
<%= render 'form' %>

<%= link_to 'Back', business_program_campaigns_path %>

app/views/businesses/programs/campaigns/show.html.erb
<% title "Campaign: #{@campaign.name}" %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @campaign.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @campaign.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @campaign.end_date %>
</p>

<p>
  <b>Camapign Type:</b>
  <%= Campaign::CTYPE.key(@campaign.ctype) %>
</p>

<p>
  <b>Business:</b>
  <%= @campaign.program.business.try(:name) %>
</p>

<p>
  <b>Measurement Type:</b>
  <%= @campaign.measurement_type.try(:name) %>
</p>
<p>
  <b>Initial User Account Amount:</b>
  <%= @campaign.initial_amount %>
</p>
<p>
  <b>Targeted to:</b>
  <%unless @campaign.targets.empty?%>
    <%= Target::TARGETS_LABELS[@campaign.targets.first.try(:name)] %>
  <%else%>
    Everyone
  <%end%>
</p>

<p>
  <b>Initial Business Account Amount:</b>
  <%= @campaign.initial_biz_amount %>
</p>
<p>
  <b>Assigned Places:</b>
  <ul>
  <%@campaign.places.each do |place|%>
    <li><%= place.name %></li>
  <%end%>
  </ul>
</p>

<p>
<%= link_to "Show Rewards", business_program_campaign_rewards_path(@business, @program,@campaign) %><br />
<%= link_to "Show Engagements", business_program_campaign_engagements_path(@business, @program, @campaign) %>
</p>

<%= link_to 'Edit', edit_business_program_campaign_path(@business,@program,@campaign) %> </br>
<%= link_to 'Back', business_program_campaigns_path(@business,@program) %>