config/routes.rb
      get  '/pending-receipts.:format', :action=> :index, :on=>:collection
    end
		resources :rewards do
			get '/claim.:format',:action=>:claim, :on =>:member
    end
    resources :cashiers do
      collection do
        get '/check_role.:format', :action => :check_user_role
        get '/business/:business_id/items.:format', :action => :list_engagements_items
        post '/ring_up.:format', :action => :ring_up
        post '/load_money.:format', :action => :load_money
        post '/charge_customer.:format', :action => :charge_customer
        get  '/receipts-merchant.:format', :action => :list_receipts_history
        get '/refund.:format', :action => :refund
      end
    end
    resource :businesses do
      get :savings, :on => :collection
      get :balance, :on => :collection

			get  '/primary_place', :action=>:primary_place, :on =>:collection
			post '/primary_place',:action=>:primary_place,  :on =>:collection
			get  '/set_rewards',  :action=>:set_rewards , :on =>:collection
			get  '/open_sign/:id',  :action=>:open_sign , :on =>:collection
			post '/open_sign/:id',  :action=>:open_sign , :on =>:collection
    end
    get '/list_all_cities.:format', :action=>:list_all_cities,:controller=>:places      
	end
	

  resources :users_snaps
	resources :users_snaps do
		get '/businesses/:business_id/places/:place_id/from_date/:from_date/to_date/:to_date'   ,:action=>:index, :on =>:collection
	end
	resources :loyal_customers
	resources :loyal_customers do
		get '/businesses/:business_id/places/:place_id/from_date/:from_date/to_date/:to_date'   ,:action=>:index, :on =>:collection
	end
	resources :program_types
	resources :programs
	resources :rewards do
	  get "update_businesses/:id"   ,:action=>:update_businesses , :on =>:collection  ,:as =>"update_business"
    get "update_programs/:id"     ,:action=>:update_programs   , :on =>:collection  ,:as =>"update_programs"
    get "update_campaigns/:id"    ,:action=>:update_campaigns  , :on =>:collection  ,:as =>"update_campaigns"
    get "update_items/:id"        ,:action=>:update_items     , :on =>:collection  ,:as =>"update_items"

	end

  resources :places do
		get "/google/:reference_id" , :action =>:google,          :on=>:member,  :as =>"google"
		get "/reset_google" ,         :action =>:reset_google ,   :on=>:member
    get '/for_businessid/:id' ,   :action=>:for_businessid,   :on =>:collection, :as=>"for_businessid"
	end

	resources :users do
    resources :transactions, :controller => 'users/transactions'
  end

  resources :templates

  resources :print_jobs
  resources :brands
  resources :brands do
    get "crop", on: :member
  end

  resources :qr_codes do
    get "update_businesses/:id" , action: :update_businesses, on: :collection , as: "update_business"
    get "update_engagements/:id", action: :update_engagements, on: :collection, as: "update_engagements"
    get "update_programs/:id", action: :update_programs, on: :collection, as: "update_programs"
    get "update_campaigns/:id" , action: :update_campaigns, on: :collection, as: "update_campaigns"
    post "panel", on: :collection
    get  "panel", on: :collection
    post "printable", on: :collection
  end

  resources :activities do
    post "earn", :on => :collection
    post "spend", :on => :collection
  end

  resources :categories , :followers, :term_and_conditions

  resources :accounts do
    resources :reports, :only => [:create, :show, :index]
  end

  resources :transactions, :only => [:index, :show] do
    member do
      post :refund
    end
  end

  resources :businesses do
    
    post :mark_as_featured
    post :mark_as_unfeatured

	  get "update_cities/:id", :action=>:update_cities, :on =>:collection, :as =>"update_cities"
	  get "update_users/:id", :action=>:update_users, :on =>:collection, :as =>"update_users"
	  get '/update_currencies/:country_id', :action=>:update_currencies, :on=> :collection, :as=>"update_currencies"
	  get "update_countries.:format",:action=>:update_countries, :on =>:collection, :as =>"update_countries"
	  get "check_primary_place/:id", :action=>:check_primary_place , :on =>:collection ,:as =>"check_primary_place"
	  get "list_campaign_transactions/:c_id", :action=> :list_campaign_transactions, :on=>:member, :as=> "list_campaign_transactions"
	  get "list_enrolled_customers/:c_id", :action=> :list_enrolled_customers, :on=>:member, :as=> "list_enrolled_customers"
	  get "list_all_enrolled_customers", :action=> :list_all_enrolled_customers, :on=> :member, :as=>"list_all_enrolled_customers"
    get '/country_code', :action => :country_code, :on =>:member
    get '/choose_campaign_type', :action => :choose_campaign_type, :on => :member
    post '/new_campaign_type', :action => :new_campaign_type, :on => :member

    resources :transactions, :controller => "businesses/transactions", :only => [:index]

    resources :measurement_types, :controller => "businesses/measurement_types"
    resources :items, :controller => "businesses/items"
    resources :places, :controller => "businesses/places" do
      resources :items, :controller => "businesses/places/items"
    end

    resources :programs , :controller => "businesses/programs" do
      resources :campaigns , :controller => "businesses/programs/campaigns" do
        resources :engagements,:controller => "businesses/programs/campaigns/engagements" do
          post "change_status"   ,:on =>:member
	        get "stamps", :on => :collection
        end
        resources :places , :only=>[:issue_code] do
          get "issue_code" ,:on =>:member
        end
	      resources :rewards, :controller=>"businesses/programs/campaigns/rewards" do
	        post "/crop_image",:action=>:crop_image
        end
     end
    end
    resources :rewards
    resources :campaigns,:controller => "businesses/campaigns" do
      post "/crop_image",:action=>:crop_image
    end
    resources :spend_campaigns,:controller => "businesses/spend_campaigns"
    resources :cash_campaigns,:controller => "businesses/cash_campaigns" do
      post '/start_campaign', :action => :start_campaign, :on => :member
      post '/stop_campaign', :action => :stop_campaign, :on => :member
    end

    resource :cashbox, :only => [:show, :edit, :update], :controller => "businesses/cashboxes"
  end
  resources :users_management do
    member do
      post "withdraw_account", :action =>:withdraw_account, :as=>"withdraw_account"
      post "deposit_account", :action =>:deposit_account, :as=>"deposit_account"
      post "redeem_rewards", :action =>:redeem_reward_for_user, :as=>"redeem_rewards"
      post "make_engagement", :action =>:make_engagement, :as=>"make_engagement"
      get  "transactions/business/:business_id/programs/:program_id",:action=>:list_transactions, :as =>"list_transactions"
      get  "list_campaigns/business/:business_id/programs/:program_id",:action=>:list_campaigns, :as =>"list_campaigns"
      get  "manage_user_accounts", :action =>:manage_user_accounts, :as=>:manage_user_accounts
      get  "redeem_rewards", :action =>:redeem_rewards, :as=>:redeem_rewards
      get  "list_engagements", :action =>:list_engagements, :as=>"list_engagements"
      get  "logged_actions", :action =>:logged_actions, :as=>"logged_actions"
      get  "all_qr_codes_transactions", :action =>:all_qr_codes_transactions, :as=>"all_qr_codes_transactions"
      get  "view_tx_details/log/:log_id", :action =>:view_tx_details, :as=>"view_tx_details"
      get  "check_txs_updates/:qr_code_id", :action => :check_txs_updates, :as=>"check_txs_updates"
      get  "transactions_report", :action => :aggregate_transactions_report, :as=>"aggregate_transactions_report"
      post :clear_image
    end

    get  "update_cities/:id",:action=>:update_cities , :on =>:collection ,:as =>"update_cities"
    post "check_attribute_availability", :action=>:check_attribute_availability,:on =>:collection ,:as =>"check_attribute_availability"
    post "resend_password", :action=>:resend_password,:on =>:collection ,:as =>"resend_password"
    post "send_confirmation_email", :action=>:send_confirmation_email,:on =>:collection ,:as =>"send_confirmation_email"

    post :enroll_in_money_program

    collection do 
      get :edit
      put :update      
    end
  end

  resources :devices do
    member do
      get :authorize
      get :deauthorize 
    end
  end
  match '/foryou'             						=> "followers#index", :as => :foryou
  match '/foryourbiz'         						=> "followers#new", :as => :foryourbiz
  match '/business_signup'                => "home#business_signup"
  match "/get_opening_hours.:format"      => "places#get_opening_hours"
  match "/get_users.:format"              => "businesses#get_users"
  match "/get_places.:format"             => "businesses#get_places"

  match "/associatable/:id/qrcodes"       => "qr_codes#list_all_associatable_qrcodes"

  match "/show_code/:id"                  => "qr_codes#show_code"
  match "/update_places"                  => "places#update_places"
  match "/auto_business"                  => "businesses#auto_business"
  match "/check_status/:id"               => "qr_codes#check_code_status"

  match "/code/:hash_code"                => "qr_codes#show"
  match "check_role"                      => "users_management#check_role"
  match "suspend_user/:id"                => "users_management#suspend_user"
  match "reactivate_user/:id"             => "users_management#reactivate_user"
  match "list_by_program_type/:program_type_id/:uid" => "users_management#list_businesses_by_program_type"
  match "enrollments/:user_id/:pt_id/:enroll" => "users_management#manage_user_enrollments"
  match "campaign_enrollments/:user_id/:c_id/:enroll" => "users_management#manage_campaign_enrollments"
  match "reissue_code/:id"                => "users_management#reissue_code"
  match "reissue_code_from_listing_txs/:id" => "users_management#reissue_code_from_listing_txs"
  
  match "/users_management/update_places/:id" =>"users_management#update_places"

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_account.html.erb
<table width="100%" class="pretty">
  <tr>
    <th><%= sortable "reportable_id", "Account" %></th>
    <th><%= sortable "activity_type", "Type" %></th>
    <th><%= sortable "engagement_id", "Engagement" %></th>
    <th><%= sortable "points", "Points" %></th>
    <th><%= sortable "place_id", "Place" %></th>
    <th><%= sortable "created_at", "Created" %></th>
  </tr>
	<% unless @reports.empty? %>
	  <% for report in @reports %>
	    <tr>
	      <td><%= report.reportable.user %></td>
	      <td><%= report.activity_type %></td>
	      <td><%= report.engagement.name %></td>
	      <td><%= report.points %></td>
	      <td><%= report.place.name %></td>
	      <td><%= report.created_at %></td>
	    </tr>
	  <% end %>
	<% else %>
		<tr>
      <td colspan="2">There are no reports</td>
    </tr>
	<% end %>
</table>

app/views/reports/_business.html.erb
<% title "Report for #{@business.name}" %>

<table width="100%" class="pretty">
  <tr>
    <th><%= sortable "reportable_id", "Business Name" %></th>
    <th><%= sortable "activity_type", "Type" %></th>
    <th><%= sortable "account_id", "Account" %></th>
    <th><%= sortable "engagement_id", "Engagement" %></th>
    <th><%= sortable "place_id", "Place" %></th>
    <th><%= sortable "created_at", "Created" %></th>
  </tr>
	<% unless @reports.empty? %>
	  <% for report in @reports %>
	    <tr>
	      <td><%= report.reportable.name %></td>
	      <td><%= report.activity_type %></td>
	      <td><%= report.account.id %></td>
	      <td><%= report.engagement.name %></td>
	      <td><%= report.place.name %> <%= link_to "(show reports by branch)", business_place_reports_path(@business, report.place) %></td>
	      <td><%= report.created_at %></td>
	    </tr>
	  <% end %>
	<% else %>
		<tr>
      <td colspan="6">There are no reports at the moment</td>
    </tr>
	<% end %>
</table>

app/views/reports/_place.html.erb
<% title "Report for #{@business.name} - #{@reportable.name} branch" %>

<table width="100%" class="pretty">
  <tr>
    <th><%= sortable "reportable_id", "Branch Name" %></th>
    <th><%= sortable "activity_type", "Type" %></th>
    <th><%= sortable "account_id", "Account" %></th>
    <th><%= sortable "engagement_id", "Engagement" %></th>
    <th><%= sortable "created_at", "Created" %></th>
  </tr>
	<% unless @reports.empty? %>
	  <% for report in @reports %>
	    <tr>
	      <td><%= report.reportable.name %></td>
	      <td><%= report.activity_type %></td>
				<td><%= report.account.id %> <%= link_to "(show reports by account)", account_reports_path(report.account.id) %></td>
	      <td><%= report.engagement.name %></td>
	      <td><%= report.created_at %></td>
	    </tr>
	  <% end %>
	<% else %>
		<tr>
      <td colspan="6">There are no reports at the moment</td>
    </tr>
	<% end %>
</table>

app/views/reports/index.html.erb
<h3><%= link_to "Go back", :back %></h3>

<div id="reports">
	<%- if @reportable.kind_of?(Place) -%>
		<%= render "place" -%>
	<%- end -%>

	<%- if @reportable.kind_of?(Account) -%>
		<%= render "account" -%>
	<%- end -%>

	<%- if @reportable.kind_of?(Business) -%>
		<%= render "business" -%>
	<%- end -%>
</div>

<%= will_paginate @reports %>

app/views/reports/show.html.erb
<% title "Report" %>

<p>
  <strong>Name:</strong>
  <%= @report.name %>
</p>
<p>
  <strong>Type:</strong>
  <%= @report.type %>
</p>

<p>
  <%= link_to "Edit", edit_report_path(@report) %> |
  <%= link_to "Destroy", @report, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", reports_path %>
</p>